// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ats_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkingCompanyATS = `-- name: ListWorkingCompanyATS :many
SELECT
    id, company_name, ats_name, ats_url, working, first_seen, last_seen
FROM
    company_ats
WHERE
    working = TRUE
ORDER BY
    last_seen DESC
`

func (q *Queries) ListWorkingCompanyATS(ctx context.Context) ([]CompanyAt, error) {
	rows, err := q.db.Query(ctx, listWorkingCompanyATS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyAt
	for rows.Next() {
		var i CompanyAt
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.AtsName,
			&i.AtsUrl,
			&i.Working,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompanyATSWorking = `-- name: SetCompanyATSWorking :exec
UPDATE
    company_ats
SET
    working = $2
WHERE
    id = $1
`

type SetCompanyATSWorkingParams struct {
	ID      pgtype.UUID `json:"id"`
	Working bool        `json:"working"`
}

func (q *Queries) SetCompanyATSWorking(ctx context.Context, arg SetCompanyATSWorkingParams) error {
	_, err := q.db.Exec(ctx, setCompanyATSWorking, arg.ID, arg.Working)
	return err
}

const upsertCompanyATS = `-- name: UpsertCompanyATS :one
INSERT INTO company_ats (company_name, ats_name, ats_url)
    VALUES ($1, $2, $3)
ON CONFLICT (ats_url)
    DO UPDATE SET
        last_seen = NOW(),
        company_name = EXCLUDED.company_name
    RETURNING
        id, company_name, ats_name, ats_url, working, first_seen, last_seen
`

type UpsertCompanyATSParams struct {
	CompanyName string `json:"company_name"`
	AtsName     string `json:"ats_name"`
	AtsUrl      string `json:"ats_url"`
}

func (q *Queries) UpsertCompanyATS(ctx context.Context, arg UpsertCompanyATSParams) (CompanyAt, error) {
	row := q.db.QueryRow(ctx, upsertCompanyATS, arg.CompanyName, arg.AtsName, arg.AtsUrl)
	var i CompanyAt
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.AtsName,
		&i.AtsUrl,
		&i.Working,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}
