// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT
    COUNT(*)::bigint
FROM
    jobs
WHERE
    (COALESCE(cardinality($1::text[]), 0) = 0
        OR EXISTS (
            SELECT
                1
            FROM
                unnest($1::text[]) AS needle
            WHERE
                company ILIKE needle ESCAPE '\'
                OR role_title ILIKE needle ESCAPE '\'
                OR COALESCE(description, '') ILIKE needle ESCAPE '\'
                OR source_name ILIKE needle ESCAPE '\'
                OR COALESCE(job_type, '') ILIKE needle ESCAPE '\'
                OR EXISTS (
                    SELECT
                        1
                    FROM
                        unnest(COALESCE(locations, ARRAY[]::text[])) AS loc
                    WHERE
                        loc ILIKE needle ESCAPE '\')))
    AND ($2::text = ''
        OR job_type = $2)
    AND (COALESCE(cardinality($3::text[]), 0) = 0
        OR EXISTS (
            SELECT
                1
            FROM
                unnest(COALESCE(locations, ARRAY[]::text[])) AS loc
                JOIN unnest($3::text[]) AS needle ON loc ILIKE needle ESCAPE '\'))
    AND ($4::text = ''
        OR source_name = $4)
    AND ($5::int = 0
        OR first_seen >= NOW() - ($5::int * INTERVAL '1 hour'))
    AND (NOT $6::bool
        OR EXISTS (
            SELECT
                1
            FROM
                user_saved_jobs s
            WHERE
                s.user_id = $7
                AND s.job_id = id))
`

type CountJobsParams struct {
	Q               []string    `json:"q"`
	FilterType      string      `json:"filter_type"`
	FilterLocations []string    `json:"filter_locations"`
	FilterSource    string      `json:"filter_source"`
	RecencyHours    int32       `json:"recency_hours"`
	FilterSaved     bool        `json:"filter_saved"`
	UserID          pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs,
		arg.Q,
		arg.FilterType,
		arg.FilterLocations,
		arg.FilterSource,
		arg.RecencyHours,
		arg.FilterSaved,
		arg.UserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11, '{}'::jsonb))
RETURNING
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
`

type CreateJobParams struct {
	SourceUrl       string             `json:"source_url"`
	SourceName      string             `json:"source_name"`
	FirstSeen       pgtype.Timestamptz `json:"first_seen"`
	ApplicationLink string             `json:"application_link"`
	Company         *string            `json:"company"`
	RoleTitle       *string            `json:"role_title"`
	Locations       []string           `json:"locations"`
	JobType         *string            `json:"job_type"`
	Description     *string            `json:"description"`
	IsAts           *bool              `json:"is_ats"`
	Metadata        interface{}        `json:"metadata"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.SourceUrl,
		arg.SourceName,
		arg.FirstSeen,
		arg.ApplicationLink,
		arg.Company,
		arg.RoleTitle,
		arg.Locations,
		arg.JobType,
		arg.Description,
		arg.IsAts,
		arg.Metadata,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceName,
		&i.FirstSeen,
		&i.ApplicationLink,
		&i.Company,
		&i.RoleTitle,
		&i.Locations,
		&i.JobType,
		&i.Description,
		&i.IsAts,
		&i.Metadata,
		&i.Embedding,
	)
	return i, err
}

const findJobForATSPosting = `-- name: FindJobForATSPosting :one
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
WHERE
    application_link = ANY ($1::text[])
    OR ($2::text <> ''
        AND application_link ~ $2)
LIMIT 1
`

type FindJobForATSPostingParams struct {
	Links     []string `json:"links"`
	LinkRegex string   `json:"link_regex"`
}

func (q *Queries) FindJobForATSPosting(ctx context.Context, arg FindJobForATSPostingParams) (Job, error) {
	row := q.db.QueryRow(ctx, findJobForATSPosting, arg.Links, arg.LinkRegex)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceName,
		&i.FirstSeen,
		&i.ApplicationLink,
		&i.Company,
		&i.RoleTitle,
		&i.Locations,
		&i.JobType,
		&i.Description,
		&i.IsAts,
		&i.Metadata,
		&i.Embedding,
	)
	return i, err
}

const getJobsByCompany = `-- name: GetJobsByCompany :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
WHERE
    company = $1
`

func (q *Queries) GetJobsByCompany(ctx context.Context, company *string) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Description,
			&i.IsAts,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsLimit = `-- name: GetJobsLimit :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
ORDER BY
    first_seen DESC
LIMIT $1
`

func (q *Queries) GetJobsLimit(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Description,
			&i.IsAts,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsStats = `-- name: GetJobsStats :one
SELECT
    (
        SELECT
            COUNT(*)::bigint
        FROM
            jobs) AS total_jobs,
    (
        SELECT
            COUNT(*)::bigint
        FROM
            jobs
        WHERE
            first_seen >= date_trunc('week', NOW())) AS added_this_week,
    (
        SELECT
            COUNT(DISTINCT company)::bigint
        FROM
            jobs) AS total_companies,
    (
        SELECT
            first_seen
        FROM
            jobs
        ORDER BY
            first_seen DESC
        LIMIT 1) AS last_updated
`

type GetJobsStatsRow struct {
	TotalJobs      int64              `json:"total_jobs"`
	AddedThisWeek  int64              `json:"added_this_week"`
	TotalCompanies int64              `json:"total_companies"`
	LastUpdated    pgtype.Timestamptz `json:"last_updated"`
}

func (q *Queries) GetJobsStats(ctx context.Context) (GetJobsStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobsStats)
	var i GetJobsStatsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.AddedThisWeek,
		&i.TotalCompanies,
		&i.LastUpdated,
	)
	return i, err
}

const listJobLocations = `-- name: ListJobLocations :many
SELECT DISTINCT
    TRIM(loc) AS location
FROM
    jobs
    CROSS JOIN LATERAL unnest(COALESCE(locations, ARRAY[]::text[])) AS loc
WHERE
    TRIM(loc) <> ''
ORDER BY
    location
`

func (q *Queries) ListJobLocations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listJobLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
WHERE
    (COALESCE(cardinality($1::text[]), 0) = 0
        OR EXISTS (
            SELECT
                1
            FROM
                unnest($1::text[]) AS needle
            WHERE
                company ILIKE needle ESCAPE '\'
                OR role_title ILIKE needle ESCAPE '\'
                OR COALESCE(description, '') ILIKE needle ESCAPE '\'
                OR source_name ILIKE needle ESCAPE '\'
                OR COALESCE(job_type, '') ILIKE needle ESCAPE '\'
                OR EXISTS (
                    SELECT
                        1
                    FROM
                        unnest(COALESCE(locations, ARRAY[]::text[])) AS loc
                    WHERE
                        loc ILIKE needle ESCAPE '\')))
    AND ($2::text = ''
        OR job_type = $2)
    AND (COALESCE(cardinality($3::text[]), 0) = 0
        OR EXISTS (
            SELECT
                1
            FROM
                unnest(COALESCE(locations, ARRAY[]::text[])) AS loc
                JOIN unnest($3::text[]) AS needle ON loc ILIKE needle ESCAPE '\'))
    AND ($4::text = ''
        OR source_name = $4)
    AND ($5::int = 0
        OR first_seen >= NOW() - ($5::int * INTERVAL '1 hour'))
    AND (NOT $6::bool
        OR EXISTS (
            SELECT
                1
            FROM
                user_saved_jobs s
            WHERE
                s.user_id = $7
                AND s.job_id = id))
ORDER BY
    CASE
    WHEN $8::text = 'company'
        AND $9::text = 'asc' THEN
        lower(COALESCE(company, ''))
    WHEN $8::text = 'role'
        AND $9::text = 'asc' THEN
        lower(COALESCE(role_title, ''))
    WHEN $8::text = 'type'
        AND $9::text = 'asc' THEN
        lower(COALESCE(job_type, ''))
    WHEN $8::text = 'location'
        AND $9::text = 'asc' THEN
        lower(COALESCE(locations[1], ''))
    END ASC NULLS LAST,
    CASE
    WHEN $8::text = 'company'
        AND $9::text = 'desc' THEN
        lower(COALESCE(company, ''))
    WHEN $8::text = 'role'
        AND $9::text = 'desc' THEN
        lower(COALESCE(role_title, ''))
    WHEN $8::text = 'type'
        AND $9::text = 'desc' THEN
        lower(COALESCE(job_type, ''))
    WHEN $8::text = 'location'
        AND $9::text = 'desc' THEN
        lower(COALESCE(locations[1], ''))
    END DESC NULLS LAST,
    CASE
    WHEN $8::text = 'posted'
        AND $9::text = 'asc' THEN
        first_seen
    END ASC NULLS LAST,
    CASE
    WHEN $8::text = 'posted'
        AND $9::text = 'desc' THEN
        first_seen
    END DESC NULLS LAST,
    first_seen DESC,
    id ASC
LIMIT $11 OFFSET $10
`

type SearchJobsParams struct {
	Q               []string    `json:"q"`
	FilterType      string      `json:"filter_type"`
	FilterLocations []string    `json:"filter_locations"`
	FilterSource    string      `json:"filter_source"`
	RecencyHours    int32       `json:"recency_hours"`
	FilterSaved     bool        `json:"filter_saved"`
	UserID          pgtype.UUID `json:"user_id"`
	SortBy          string      `json:"sort_by"`
	SortDir         string      `json:"sort_dir"`
	RowOffset       int32       `json:"row_offset"`
	RowLimit        int32       `json:"row_limit"`
}

func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, searchJobs,
		arg.Q,
		arg.FilterType,
		arg.FilterLocations,
		arg.FilterSource,
		arg.RecencyHours,
		arg.FilterSaved,
		arg.UserID,
		arg.SortBy,
		arg.SortDir,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Description,
			&i.IsAts,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobDescription = `-- name: UpdateJobDescription :execrows
UPDATE
    jobs
SET
    description = $1,
    is_ats = TRUE
WHERE
    id = $2
`

type UpdateJobDescriptionParams struct {
	Description *string     `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateJobDescription(ctx context.Context, arg UpdateJobDescriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateJobDescription, arg.Description, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
