// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, is_ats, metadata)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, COALESCE($10, '{}'::jsonb))
RETURNING
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
`

type CreateJobParams struct {
	SourceUrl       string             `json:"source_url"`
	SourceName      string             `json:"source_name"`
	FirstSeen       pgtype.Timestamptz `json:"first_seen"`
	ApplicationLink string             `json:"application_link"`
	Company         *string            `json:"company"`
	RoleTitle       *string            `json:"role_title"`
	Locations       []string           `json:"locations"`
	JobType         *string            `json:"job_type"`
	IsAts           *bool              `json:"is_ats"`
	Column10        interface{}        `json:"column_10"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.SourceUrl,
		arg.SourceName,
		arg.FirstSeen,
		arg.ApplicationLink,
		arg.Company,
		arg.RoleTitle,
		arg.Locations,
		arg.JobType,
		arg.IsAts,
		arg.Column10,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceName,
		&i.FirstSeen,
		&i.ApplicationLink,
		&i.Company,
		&i.RoleTitle,
		&i.Locations,
		&i.JobType,
		&i.Description,
		&i.IsAts,
		&i.Metadata,
		&i.Embedding,
	)
	return i, err
}

const getJobsByCompany = `-- name: GetJobsByCompany :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
WHERE
    company = $1
`

func (q *Queries) GetJobsByCompany(ctx context.Context, company *string) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Description,
			&i.IsAts,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsLimit = `-- name: GetJobsLimit :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
ORDER BY
    first_seen DESC
LIMIT $1
`

func (q *Queries) GetJobsLimit(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Description,
			&i.IsAts,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsStats = `-- name: GetJobsStats :one
SELECT
    (
        SELECT
            COUNT(*)::bigint
        FROM
            jobs) AS total_jobs,
    (
        SELECT
            COUNT(*)::bigint
        FROM
            jobs
        WHERE
            first_seen >= date_trunc('week', NOW())) AS added_this_week,
    (
        SELECT
            COUNT(DISTINCT company)::bigint
        FROM
            jobs) AS total_companies,
    (
        SELECT
            first_seen
        FROM
            jobs
        ORDER BY
            first_seen DESC
        LIMIT 1) AS last_updated
`

type GetJobsStatsRow struct {
	TotalJobs      int64              `json:"total_jobs"`
	AddedThisWeek  int64              `json:"added_this_week"`
	TotalCompanies int64              `json:"total_companies"`
	LastUpdated    pgtype.Timestamptz `json:"last_updated"`
}

func (q *Queries) GetJobsStats(ctx context.Context) (GetJobsStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobsStats)
	var i GetJobsStatsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.AddedThisWeek,
		&i.TotalCompanies,
		&i.LastUpdated,
	)
	return i, err
}
