// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CompanyAt struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyName string             `json:"company_name"`
	AtsName     string             `json:"ats_name"`
	AtsUrl      string             `json:"ats_url"`
	Working     bool               `json:"working"`
	FirstSeen   pgtype.Timestamptz `json:"first_seen"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

type Job struct {
	ID              pgtype.UUID        `json:"id"`
	SourceUrl       string             `json:"source_url"`
	SourceName      string             `json:"source_name"`
	FirstSeen       pgtype.Timestamptz `json:"first_seen"`
	ApplicationLink string             `json:"application_link"`
	Company         *string            `json:"company"`
	RoleTitle       *string            `json:"role_title"`
	Locations       []string           `json:"locations"`
	JobType         *string            `json:"job_type"`
	Metadata        []byte             `json:"metadata"`
	Embedding       *pgvector.Vector   `json:"embedding"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	DiscordID *string            `json:"discord_id"`
	IsAdmin   bool               `json:"is_admin"`
	IsActive  bool               `json:"is_active"`
	IsPremium bool               `json:"is_premium"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserSavedJob struct {
	UserID pgtype.UUID `json:"user_id"`
	JobID  pgtype.UUID `json:"job_id"`
}
