// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, metadata)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, '{}'::jsonb) -- If $9 is null, use the default
)
RETURNING
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, metadata, embedding
`

type CreateJobParams struct {
	SourceUrl       string             `json:"source_url"`
	SourceName      string             `json:"source_name"`
	FirstSeen       pgtype.Timestamptz `json:"first_seen"`
	ApplicationLink string             `json:"application_link"`
	Company         *string            `json:"company"`
	RoleTitle       *string            `json:"role_title"`
	Locations       []string           `json:"locations"`
	JobType         *string            `json:"job_type"`
	Column9         interface{}        `json:"column_9"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.SourceUrl,
		arg.SourceName,
		arg.FirstSeen,
		arg.ApplicationLink,
		arg.Company,
		arg.RoleTitle,
		arg.Locations,
		arg.JobType,
		arg.Column9,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceName,
		&i.FirstSeen,
		&i.ApplicationLink,
		&i.Company,
		&i.RoleTitle,
		&i.Locations,
		&i.JobType,
		&i.Metadata,
		&i.Embedding,
	)
	return i, err
}

const getJobsByCompany = `-- name: GetJobsByCompany :many
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, metadata, embedding
FROM
    jobs
WHERE
    company = $1
`

func (q *Queries) GetJobsByCompany(ctx context.Context, company *string) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.SourceName,
			&i.FirstSeen,
			&i.ApplicationLink,
			&i.Company,
			&i.RoleTitle,
			&i.Locations,
			&i.JobType,
			&i.Metadata,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
