// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_search_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSavedSearch = `-- name: CreateUserSavedSearch :one
INSERT INTO user_saved_searches (user_id, name, q, job_type, location, recency, saved_only, sort_by, sort_dir)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, user_id, name, q, job_type, location, recency, saved_only, sort_by, sort_dir, created_at, updated_at
`

type CreateUserSavedSearchParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	Q         string      `json:"q"`
	JobType   string      `json:"job_type"`
	Location  string      `json:"location"`
	Recency   string      `json:"recency"`
	SavedOnly bool        `json:"saved_only"`
	SortBy    string      `json:"sort_by"`
	SortDir   string      `json:"sort_dir"`
}

func (q *Queries) CreateUserSavedSearch(ctx context.Context, arg CreateUserSavedSearchParams) (UserSavedSearch, error) {
	row := q.db.QueryRow(ctx, createUserSavedSearch,
		arg.UserID,
		arg.Name,
		arg.Q,
		arg.JobType,
		arg.Location,
		arg.Recency,
		arg.SavedOnly,
		arg.SortBy,
		arg.SortDir,
	)
	var i UserSavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Q,
		&i.JobType,
		&i.Location,
		&i.Recency,
		&i.SavedOnly,
		&i.SortBy,
		&i.SortDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSavedSearch = `-- name: DeleteUserSavedSearch :execrows
DELETE FROM user_saved_searches
WHERE id = $1
    AND user_id = $2
`

type DeleteUserSavedSearchParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserSavedSearch(ctx context.Context, arg DeleteUserSavedSearchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSavedSearch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSavedSearch = `-- name: GetUserSavedSearch :one
SELECT
    id, user_id, name, q, job_type, location, recency, saved_only, sort_by, sort_dir, created_at, updated_at
FROM
    user_saved_searches
WHERE
    id = $1
    AND user_id = $2
`

type GetUserSavedSearchParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUserSavedSearch(ctx context.Context, arg GetUserSavedSearchParams) (UserSavedSearch, error) {
	row := q.db.QueryRow(ctx, getUserSavedSearch, arg.ID, arg.UserID)
	var i UserSavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Q,
		&i.JobType,
		&i.Location,
		&i.Recency,
		&i.SavedOnly,
		&i.SortBy,
		&i.SortDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSavedSearches = `-- name: ListUserSavedSearches :many
SELECT
    id, user_id, name, q, job_type, location, recency, saved_only, sort_by, sort_dir, created_at, updated_at
FROM
    user_saved_searches
WHERE
    user_id = $1
ORDER BY
    name ASC
`

func (q *Queries) ListUserSavedSearches(ctx context.Context, userID pgtype.UUID) ([]UserSavedSearch, error) {
	rows, err := q.db.Query(ctx, listUserSavedSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSavedSearch
	for rows.Next() {
		var i UserSavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Q,
			&i.JobType,
			&i.Location,
			&i.Recency,
			&i.SavedOnly,
			&i.SortBy,
			&i.SortDir,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSavedSearch = `-- name: UpdateUserSavedSearch :one
UPDATE
    user_saved_searches
SET
    name = $3,
    q = $4,
    job_type = $5,
    location = $6,
    recency = $7,
    saved_only = $8,
    sort_by = $9,
    sort_dir = $10,
    updated_at = NOW()
WHERE
    id = $1
    AND user_id = $2
RETURNING
    id, user_id, name, q, job_type, location, recency, saved_only, sort_by, sort_dir, created_at, updated_at
`

type UpdateUserSavedSearchParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	Q         string      `json:"q"`
	JobType   string      `json:"job_type"`
	Location  string      `json:"location"`
	Recency   string      `json:"recency"`
	SavedOnly bool        `json:"saved_only"`
	SortBy    string      `json:"sort_by"`
	SortDir   string      `json:"sort_dir"`
}

func (q *Queries) UpdateUserSavedSearch(ctx context.Context, arg UpdateUserSavedSearchParams) (UserSavedSearch, error) {
	row := q.db.QueryRow(ctx, updateUserSavedSearch,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Q,
		arg.JobType,
		arg.Location,
		arg.Recency,
		arg.SavedOnly,
		arg.SortBy,
		arg.SortDir,
	)
	var i UserSavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Q,
		&i.JobType,
		&i.Location,
		&i.Recency,
		&i.SavedOnly,
		&i.SortBy,
		&i.SortDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
