// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_job_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJob = `-- name: GetJob :one
SELECT
    id, source_url, source_name, first_seen, application_link, company, role_title, locations, job_type, description, is_ats, metadata, embedding
FROM
    jobs
WHERE
    id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceName,
		&i.FirstSeen,
		&i.ApplicationLink,
		&i.Company,
		&i.RoleTitle,
		&i.Locations,
		&i.JobType,
		&i.Description,
		&i.IsAts,
		&i.Metadata,
		&i.Embedding,
	)
	return i, err
}

const listSavedJobIDsAmong = `-- name: ListSavedJobIDsAmong :many
SELECT
    job_id
FROM
    user_saved_jobs
WHERE
    user_id = $1
    AND job_id = ANY ($2::uuid[])
`

type ListSavedJobIDsAmongParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	JobIds []pgtype.UUID `json:"job_ids"`
}

func (q *Queries) ListSavedJobIDsAmong(ctx context.Context, arg ListSavedJobIDsAmongParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSavedJobIDsAmong, arg.UserID, arg.JobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var job_id pgtype.UUID
		if err := rows.Scan(&job_id); err != nil {
			return nil, err
		}
		items = append(items, job_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :exec
INSERT INTO user_saved_jobs (user_id, job_id)
    VALUES ($1, $2)
ON CONFLICT (user_id, job_id)
    DO NOTHING
`

type SaveJobParams struct {
	UserID pgtype.UUID `json:"user_id"`
	JobID  pgtype.UUID `json:"job_id"`
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.Exec(ctx, saveJob, arg.UserID, arg.JobID)
	return err
}

const unsaveJob = `-- name: UnsaveJob :exec
DELETE FROM user_saved_jobs
WHERE user_id = $1
    AND job_id = $2
`

type UnsaveJobParams struct {
	UserID pgtype.UUID `json:"user_id"`
	JobID  pgtype.UUID `json:"job_id"`
}

func (q *Queries) UnsaveJob(ctx context.Context, arg UnsaveJobParams) error {
	_, err := q.db.Exec(ctx, unsaveJob, arg.UserID, arg.JobID)
	return err
}
